using System.Net;
using System.Security.Cryptography;
using System.Text;

namespace Orbit.Core.Settings;

/// <summary>
/// Helpers for Orbit↔Hermes pairing (ADR 0022). Hermes API auth is Bearer API_SERVER_KEY only —
/// there is no OAuth device flow for OpenAI-compatible clients. Provider login, Telegram, and
/// other Hermes admin live on the web dashboard (:9119), not the API (:8642).
/// </summary>
public static class HermesPairing
{
    public const string LocalDefaultBaseUrl = "http://127.0.0.1:8642";

    public const string LocalDefaultDashboardUrl = "http://127.0.0.1:9119";

    public const int ApiPort = 8642;

    public const int DashboardPort = 9119;

    public const string LocalBundleFolderName = "hermes-local";

    /// <summary>Generate a Hermes API_SERVER_KEY / Orbit sidecar value (64 hex chars).</summary>
    public static string GenerateApiServerKey() =>
        Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();

    /// <summary>Generate a dashboard basic-auth password (24 url-safe chars).</summary>
    public static string GenerateDashboardPassword()
    {
        const string alphabet = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789";
        var bytes = RandomNumberGenerator.GetBytes(24);
        var chars = new char[24];
        for (var i = 0; i < chars.Length; i++)
        {
            chars[i] = alphabet[bytes[i] % alphabet.Length];
        }

        return new string(chars);
    }

    /// <summary>
    /// Map Hermes API base URL → dashboard URL (same host/scheme, port 9119).
    /// Returns null when the API URL is invalid.
    /// </summary>
    public static string? DeriveDashboardUrl(string? hermesApiBaseUrl)
    {
        if (!HermesUrlValidation.TryValidate(hermesApiBaseUrl, out var normalized, out _))
        {
            return null;
        }

        var uri = new Uri(normalized!);
        var builder = new UriBuilder(uri)
        {
            Port = DashboardPort,
            Path = string.Empty,
            Query = string.Empty,
            Fragment = string.Empty,
        };
        return builder.Uri.ToString().TrimEnd('/');
    }

    /// <summary>
    /// Build the Core URL Hermes should call. Prefer an explicit LAN/Tailscale bind over loopback
    /// when Hermes runs on another machine.
    /// </summary>
    public static string BuildReachableCoreUrl(string? bindAddress, string? coreHostBaseUrl)
    {
        if (!string.IsNullOrWhiteSpace(coreHostBaseUrl) &&
            Uri.TryCreate(coreHostBaseUrl.Trim(), UriKind.Absolute, out var configured) &&
            (configured.Scheme == Uri.UriSchemeHttp || configured.Scheme == Uri.UriSchemeHttps))
        {
            var bind = (bindAddress ?? string.Empty).Trim();
            if (!string.IsNullOrEmpty(bind) &&
                !IsLoopbackHostName(bind) &&
                !string.Equals(bind, "0.0.0.0", StringComparison.OrdinalIgnoreCase) &&
                !string.Equals(bind, "*", StringComparison.OrdinalIgnoreCase) &&
                !string.Equals(bind, "::", StringComparison.OrdinalIgnoreCase))
            {
                var builder = new UriBuilder(configured) { Host = bind };
                return builder.Uri.ToString().TrimEnd('/');
            }

            return configured.ToString().TrimEnd('/');
        }

        var host = string.IsNullOrWhiteSpace(bindAddress) ? "127.0.0.1" : bindAddress.Trim();
        if (string.Equals(host, "0.0.0.0", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(host, "*", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(host, "::", StringComparison.OrdinalIgnoreCase))
        {
            host = "127.0.0.1";
        }

        return $"http://{host}:8741";
    }

    /// <summary>Clipboard / .env snippet Hermes needs for Orbit.Mcp.</summary>
    public static string BuildCoreEnvSnippet(string orbitCoreUrl, string? orbitApiKey)
    {
        var key = string.IsNullOrWhiteSpace(orbitApiKey) ? "<paste-core-host-api-key>" : orbitApiKey.Trim();
        var sb = new StringBuilder();
        sb.AppendLine("# Paste into ~/.hermes/.env on the Hermes host, then reload MCP.");
        sb.AppendLine($"ORBIT_CORE_URL={orbitCoreUrl.Trim().TrimEnd('/')}");
        sb.AppendLine($"ORBIT_API_KEY={key}");
        return sb.ToString();
    }

    public static string BuildLocalComposeYaml() =>
        """
        # Generated by Orbit Settings → Prepare local Hermes folder (ADR 0022).
        # From this directory: docker compose up -d
        # CMD must be `gateway run` so the API server starts under s6.
        # Bare `hermes` is an interactive CLI that exits without a TTY (restart loop).
        # API (Orbit chat):     http://127.0.0.1:8642
        # Dashboard (setup UI): http://127.0.0.1:9119  ← provider login, Telegram, etc.
        services:
          hermes:
            image: nousresearch/hermes-agent:latest
            restart: unless-stopped
            command: ["gateway", "run"]
            ports:
              - "8642:8642"
              - "9119:9119"
            volumes:
              - ./hermes-data:/opt/data
            environment:
              API_SERVER_ENABLED: "true"
              API_SERVER_HOST: "0.0.0.0"
              API_SERVER_KEY: "${API_SERVER_KEY}"
              HERMES_DASHBOARD: "1"
              HERMES_DASHBOARD_HOST: "0.0.0.0"
              HERMES_DASHBOARD_PORT: "9119"
              HERMES_DASHBOARD_BASIC_AUTH_USERNAME: "${HERMES_DASHBOARD_BASIC_AUTH_USERNAME}"
              HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: "${HERMES_DASHBOARD_BASIC_AUTH_PASSWORD}"
              HERMES_DASHBOARD_BASIC_AUTH_SECRET: "${HERMES_DASHBOARD_BASIC_AUTH_SECRET}"
              ORBIT_CORE_URL: "${ORBIT_CORE_URL}"
              ORBIT_API_KEY: "${ORBIT_API_KEY}"
        """.Replace("\r\n", "\n").TrimStart() + "\n";

    public static string BuildLocalEnvFile(
        string apiServerKey,
        string orbitCoreUrl,
        string? orbitApiKey,
        string dashboardUsername,
        string dashboardPassword,
        string dashboardSecret)
    {
        var key = string.IsNullOrWhiteSpace(orbitApiKey) ? string.Empty : orbitApiKey.Trim();
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Orbit — do not commit.");
        sb.AppendLine($"API_SERVER_KEY={apiServerKey.Trim()}");
        sb.AppendLine($"ORBIT_CORE_URL={orbitCoreUrl.Trim().TrimEnd('/')}");
        sb.AppendLine($"ORBIT_API_KEY={key}");
        sb.AppendLine($"HERMES_DASHBOARD_BASIC_AUTH_USERNAME={dashboardUsername.Trim()}");
        sb.AppendLine($"HERMES_DASHBOARD_BASIC_AUTH_PASSWORD={dashboardPassword.Trim()}");
        sb.AppendLine($"HERMES_DASHBOARD_BASIC_AUTH_SECRET={dashboardSecret.Trim()}");
        return sb.ToString();
    }

    private static bool IsLoopbackHostName(string host)
    {
        if (string.Equals(host, "localhost", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(host, "127.0.0.1", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(host, "::1", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return IPAddress.TryParse(host, out var address) && IPAddress.IsLoopback(address);
    }
}
